/**
 * Date mock pentru colecția de flori (fără backend).
 */
window.FLORI_MOCK = [
  {
    id: 'trandafir-vechi-roz',
    nume: 'Trandafir vechi „Marie Louise”',
    categorie: 'trandafiri',
    descriereScurta: 'Trandafir istoric, roz intens, cu miros puternic.',
    descriere: 'Varietate istorică din secolul XIX, cu flori duble roz intens și un parfum memorabil. Rezistent la boli, preferă soare și sol bine drenat.',
    imagine: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=600&q=80',
    sezon: 'Mai – Octombrie',
    inaltime: '80–120 cm',
  },
  {
    id: 'peonie-alba',
    nume: 'Peonie „Duchesse de Nemours”',
    categorie: 'peonii',
    descriereScurta: 'Peonie albă dublă, clasică de grădină.',
    descriere: 'Una dintre cele mai iubite peonii albe, cu flori pline și un parfum delicat. Se deschide în mai–iunie și preferă locuri semi-umbrate.',
    imagine: 'https://images.unsplash.com/photo-1520763185298-1b434c919102?w=600&q=80',
    sezon: 'Mai – Iunie',
    inaltime: '70–90 cm',
  },
  {
    id: 'lalele-tulipan',
    nume: 'Lalele „Queen of Night”',
    categorie: 'lalele',
    descriereScurta: 'Lalele aproape negre, spectaculoase în borduri.',
    descriere: 'Tulipan înalt, de culoare violet-închis aproape neagră. Ideal pentru contrast în grădini de primăvară. Înflorește în aprilie–mai.',
    imagine: 'https://images.unsplash.com/photo-1520763185298-1b434c919102?w=600&q=80',
    sezon: 'Aprilie – Mai',
    inaltime: '50–60 cm',
  },
  {
    id: 'trandafir-alb',
    nume: 'Trandafir „Iceberg”',
    categorie: 'trandafiri',
    descriereScurta: 'Trandafir alb floribunda, foarte florifer.',
    descriere: 'Trandafir alb, rezistent la frig și boli, cu flori în ciorchine. Înflorește din mai până toamna târziu. Perfect pentru garduri și arbori.',
    imagine: 'https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?w=600&q=80',
    sezon: 'Mai – Noiembrie',
    inaltime: '100–150 cm',
  },
  {
    id: 'lavanda',
    nume: 'Lavandă „Hidcote”',
    categorie: 'aromate',
    descriereScurta: 'Lavandă compactă, violet închis, foarte aromată.',
    descriere: 'Lavandă englezească cu flori violet-închis și frunziș argintiu. Atrage albinele și e excelentă pentru uscat sau uleiuri. Soare plin.',
    imagine: 'https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=600&q=80',
    sezon: 'Iunie – August',
    inaltime: '40–50 cm',
  },
  {
    id: 'echinacea',
    nume: 'Echinacea purpurée',
    categorie: 'perene',
    descriereScurta: 'Plantă perenă medicinală, flori roz-purpurii.',
    descriere: 'Echinacea purpurie, perenă rezistentă la secetă. Florile atrag fluturii și albinele. Se folosește și în fitoterapie. Soare, sol drenat.',
    imagine: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&q=80',
    sezon: 'Iunie – Septembrie',
    inaltime: '60–90 cm',
  },
  {
    id: 'trandafir-coral',
    nume: 'Trandafir „Westerland”',
    categorie: 'trandafiri',
    descriereScurta: 'Trandafir coral-portocaliu, parfumat.',
    descriere: 'Trandafir modern, coral-portocaliu, cu miros puternic. Rezistent și florifer. Se potrivește atât în borduri cât și tăiat în vază.',
    imagine: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=600&q=80',
    sezon: 'Mai – Octombrie',
    inaltime: '120–150 cm',
  },
  {
    id: 'peonie-roz',
    nume: 'Peonie „Sarah Bernhardt”',
    categorie: 'peonii',
    descriereScurta: 'Peonie roz pal, dublă, foarte populară.',
    descriere: 'Peonie roz deschis, cu petale duble și parfum delicat. Clasică în grădini și buchete. Înflorește în mai–iunie.',
    imagine: 'https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?w=600&q=80',
    sezon: 'Mai – Iunie',
    inaltime: '80–100 cm',
  },
  {
    id: 'lalele-mix',
    nume: 'Lalele „Parrot Mix”',
    categorie: 'lalele',
    descriereScurta: 'Lalele cu petale panațate, colorate spectaculos.',
    descriere: 'Mix de lalele parrot, cu petale ondulate și culori combinate. Ideal pentru efect în grădini și în vase. Înflorește în aprilie–mai.',
    imagine: 'https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?w=600&q=80',
    sezon: 'Aprilie – Mai',
    inaltime: '45–55 cm',
  },
  {
    id: 'salvia',
    nume: 'Salvie ornamentală „Caradonna”',
    categorie: 'perene',
    descriereScurta: 'Salvie violet cu spice negre, atrage polenizatorii.',
    descriere: 'Salvie perenă cu spice violet-închis și frunze verzi. Florărit lung, de la primăvară până toamna. Soare, sol bine drenat.',
    imagine: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&q=80',
    sezon: 'Mai – Septembrie',
    inaltime: '50–60 cm',
  },
  {
    id: 'rozmarin',
    nume: 'Rozmarin officinalis',
    categorie: 'aromate',
    descriereScurta: 'Rozmarin aromatic, rezistent, albastrele.',
    descriere: 'Arbust peren mediteranean, cu frunze aromate și flori albastre. Preferă soare și sol uscat. Folosit în bucătărie și pentru atragerea insectelor utile.',
    imagine: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
    sezon: 'Martie – Mai',
    inaltime: '80–120 cm',
  },
  {
    id: 'dalia',
    nume: 'Dalia „Café au Lait”',
    categorie: 'perene',
    descriereScurta: 'Dalie mare, culoare cafea cu lapte.',
    descriere: 'Dalie decorativă cu flori foarte mari, în nuanțe de bej, crem și roz. Spectaculoasă în borduri și tăiată. Tubérculi se plantează în primăvară.',
    imagine: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&q=80',
    sezon: 'Iulie – Octombrie',
    inaltime: '100–120 cm',
  },
  {
    id: 'trandafir-galben',
    nume: 'Trandafir „Graham Thomas”',
    categorie: 'trandafiri',
    descriereScurta: 'Trandafir galben englezesc, parfumat.',
    descriere: 'Trandafir englezesc galben-auriu, cu formă de ceașcă și parfum puternic. Rezistent și sănătos. Preferă soare și sol bogat.',
    imagine: 'https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?w=600&q=80',
    sezon: 'Mai – Octombrie',
    inaltime: '120–150 cm',
  },
  {
    id: 'peonie-rosie',
    nume: 'Peonie „Red Charm”',
    categorie: 'peonii',
    descriereScurta: 'Peonie roșie dublă, bombată.',
    descriere: 'Peonie roșie intens, cu flori duble bombate. Contrast excelent cu peoniile albe și roz. Înflorește în mai–iunie.',
    imagine: 'https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?w=600&q=80',
    sezon: 'Mai – Iunie',
    inaltime: '75–85 cm',
  },
  {
    id: 'lalele-albe',
    nume: 'Lalele „White Triumphator”',
    categorie: 'lalele',
    descriereScurta: 'Lalele albe elegante, tulipan înalt.',
    descriere: 'Tulipan alb pur, înalt, ideal pentru grădini albe sau mix. Înflorește în aprilie–mai. Bulbi se plantează toamna.',
    imagine: 'https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?w=600&q=80',
    sezon: 'Aprilie – Mai',
    inaltime: '50–55 cm',
  },
  {
    id: 'menta',
    nume: 'Mentă piperită',
    categorie: 'aromate',
    descriereScurta: 'Mentă aromată, pentru ceai și grădină.',
    descriere: 'Plantă aromată perenă, cu frunze verzi și miros răcoritor. Folosită în ceaiuri și bucătărie. Preferă umbră parțială și sol umed.',
    imagine: 'https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=600&q=80',
    sezon: 'Iunie – August',
    inaltime: '30–50 cm',
  },
  {
    id: 'gaura',
    nume: 'Gaura lindheimeri',
    categorie: 'perene',
    descriereScurta: 'Perenă cu flori albe delicate, dansatoare.',
    descriere: 'Plantă perenă cu flori albe sau roz, pe tije subțiri. Rezistentă la secetă, florărit lung. Soare plin, sol drenat.',
    imagine: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&q=80',
    sezon: 'Mai – Octombrie',
    inaltime: '60–90 cm',
  },
];
